### ISSUE TITLE
Google Cloud SDK DSL

### ISSUE THREAD

**Issue by jkone27** [UnoSD/Pulumi.FSharp.Extensions#10]
is google cloud sdk DSL also supported for GCP resources?

**Comment by UnoSD** [comment]
The GCP schema seems to be there: https://github.com/pulumi/pulumi-gcp/blob/master/provider/cmd/pulumi-resource-gcp/schema.json

It may be just a case of creating another project and kicking a build, it may work straightaway; feel free to send a PR and I'll publish it.

**Comment by jkone27** [comment]
I have never used Myriad for generation, is there any sample i can refer to ? i would be glad to add the PR :) 
does it work a bit like type providers or source generators right? 👍

**Comment by UnoSD** [comment]
if I recall correctly, my build script should pick up projects by naming convention; as long as you ad a new project that matches the existing ones E.G. https://github.com/UnoSD/Pulumi.FSharp.Extensions/tree/master/Pulumi.FSharp.AzureNative it should generate it.

The only file to update is the fsproj file, all the rest stays the same, try replacing occurences of AzureNative with the name of the provider (I guess just Gcp) and kick a build `dotnet fake run build.fsx Gcp`. if that yields no errors, that likely worked and can be merged

**Comment by jkone27** [comment]
Added a test PR but have some errors:
https://github.com/UnoSD/Pulumi.FSharp.Extensions/pull/11

**Comment by UnoSD** [comment]
@jkone27 seems to be building well on my machine; "SasToken.fs" is an extra CE only for Azure, it can be removed. I'll update your PR with the working code and merge it.

**Comment by UnoSD** [comment]
in the meanwhile, I've manually uploaded the package to NuGet, so you can start using it
