### ISSUE TITLE
Pulumi.Fsharp.Gcp

### ISSUE THREAD

**Issue by jkone27** [UnoSD/Pulumi.FSharp.Extensions#12]
![image](https://user-images.githubusercontent.com/10419217/150157369-6c7090c0-fee8-403e-9f3d-bd1c896cd0d4.png)

was testing the result from fsx script but not sure it exactly working as expected, generated docs have many generic types 'a ...

doesnt seem completely right

**Comment by UnoSD** [comment]
the one you see above is not the documentation, it the actual signature of the computational expression. it looks confusing but it's just how it works behind the scenes.

what concerns me is the red squiggles you are getting, I had errors also when I tried adding a basic example, but not knowing GCP very well apart from a few more complex services, I didn't spend time checking it as I didn't know how to build a simple meaningful bucket sample. that probably requires more investigation, but I won't be able to pick it up anytime soon. like before I'm happy to review a PR you manage to make sense of it.

On a side note, the Pulumi.Gcp seems to be a "classic" library and a new GcpNative is coming up, may be not worth investing time in fixing this when a new one will replace it. would be good to try and get the new one up instead.

**Comment by jkone27** [comment]
i see if they publish the new native GCP version in Pulumi we can give it a try with that one then :) thanks a lot! anyway this is an amazing proj :)

**Comment by UnoSD** [comment]
@jkone27 you can give it another spin now (to the updated package). turns out it was a problem after the upgrade of Myriad that broke all the generated code, not just the new GCP/TLS stuff. Thanks!
