### ISSUE TITLE
CI running for a long time

### ISSUE THREAD

**Issue by LiHRaM** [UnoSD/Pulumi.FSharp.Extensions#15]
Hi,

I was wondering if you knew why sometimes the CI would just not complete running for certain packages? E.g. https://github.com/UnoSD/Pulumi.FSharp.Extensions/runs/5834434536 has been running for a while now, which I figured was normal until I looked further up the CI history and saw that some jobs had been queued for 60+ days. My previous MR's main purpose was to get the latest version of Pulumi.FSharp.Gcp, and I'm wondering if there's something missing to make that happen? Please LMK if I can help.

Edit: Example of 60+ queued job: https://github.com/UnoSD/Pulumi.FSharp.Extensions/runs/4941344244

**Comment by LiHRaM** [comment]
Since it eventually ran to completion, I'll close this issue. 😄

**Comment by UnoSD** [comment]
FYI: The pipeline in DevOps was hanging waiting for permissions. I had to manually authorize to get it started.
