### ISSUE TITLE
namespaces issues

### ISSUE THREAD

**Issue by jkone27** [UnoSD/Pulumi.FSharp.Extensions#17]
i think namespace usage of open is too complex and hard to troubleshoot, e.g. when using the simplest

Pulumi.FSharp.Kubernetes to just deploy an nginx pod in minikube, it's not really clear which namespaces are needed and what to use in open statements from the docs...

<img width="558" alt="image" src="https://user-images.githubusercontent.com/10419217/174308682-baa7a392-2b87-42a7-82fc-703f7e65bd7d.png">

**Comment by UnoSD** [comment]
see K8s example here: https://github.com/UnoSD/Pulumi.FSharp.Extensions.Examples/tree/main/Kubernetes/AKSCluster
