### ISSUE TITLE
intellisense on types

### ISSUE THREAD

**Issue by jkone27** [UnoSD/Pulumi.FSharp.Extensions#18]
maybe type intellisense could get an improvement somehow, the description of types and usage are quite complex and also seems wrong, so it's not easy to pass arguments to functions in the CE...

<img width="607" alt="image" src="https://user-images.githubusercontent.com/10419217/174616016-82c6a480-5560-41bb-8b49-fd05f139ca4b.png">

or another example...

<img width="352" alt="image" src="https://user-images.githubusercontent.com/10419217/174617201-10e991ee-32e7-4069-99e9-d64e84c89907.png">

e.g. container image is a standard ```string``` type

i think in many cases the type suggetion of intellisense are totally wrong / misleading, and could be much simplified

**Comment by UnoSD** [comment]
Due to the nature of the CE, I'm not sure much can be done, but please reopen if you have suggestions.
