### ISSUE TITLE
Resource name overload

### ISSUE THREAD

**Issue by JordanMarr** [UnoSD/Pulumi.FSharp.Extensions#7]
My issue is that Pulumi is appending generated characters to my resource names.
https://github.com/pulumi/pulumi/issues/7368

Is it possible to specify resource names in such a way that generated characters are not appended?
According the the [Pulumi docs](https://www.pulumi.com/docs/intro/concepts/resources/#names), you must do this:

```C#
var role = new Aws.Iam.Role("my-role", new Aws.Iam.RoleArgs
{
    Name = "my-role-001",
});
```

It seems that `name` in the F# builder only takes a string. Would it be possible to overload it to take a resource name that will not be changed?

**Comment by UnoSD** [comment]
That was a bit tricky from a naming perspective, but I recall I added a `resourceName` operation on the builders that should map to the name of the cloud resource (rather than the Pulumi name). It should override the auto-naming in Pulumi.

**Comment by JordanMarr** [comment]
That worked (thank you!), but with a few caveats:

1) Setting only `resourceName` results in a null ref exception for `name`. But setting both `name` and `resourceName` seems to work.  (I'm not sure if that's order dependent).

2) KeyVault.accessPolicy doesn't have a `resourceName`, only `name`. Although that may not matter since the access policies aren't visible from the resource group listing anyway.


Since you're generating the entire computation expression (correct?), I guess it's not possible (or not very easy) to simply have the `resourceName` custom operation set both?

**Comment by JordanMarr** [comment]
Btw, _really_ great idea to use Myriad here as you have done. Well done!
I used Myriad in an early alpha of [SqlHydra](https://github.com/JordanMarr/SqlHydra) to generate records from SQL Server SSDT .dacpac file, but have since pivoted to make it a dotnet tool instead.

**Comment by UnoSD** [comment]
> That worked (thank you!), but with a few caveats:
> 
> 1. Setting only `resourceName` results in a null ref exception for `name`. But setting both `name` and `resourceName` seems to work.  (I'm not sure if that's order dependent).
> 2. KeyVault.accessPolicy doesn't have a `resourceName`, only `name`. Although that may not matter since the access policies aren't visible from the resource group listing anyway.
> 
> Since you're generating the entire computation expression (correct?), I guess it's not possible (or not very easy) to simply have the `resourceName` custom operation set both?

Glad it's working; I have not had a lot of time to recently to spend on the project, so it's good to have someone else using it and getting some feedback.

1. That's expected, Pulumi requires the "name", so it makes sense it throws an exception (would be nice a more functional response, but that's not in my code).
2. Does an Access policy in KV have a name? Being part of a resource I don't know if it can have a name in Azure at all. In that case, it would make sense to have only the Pulumi name as the Azure REST API may not have a option to set it. Looking at https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/create-or-update#accesspolicyentry it does not seem to have a name.

It would be possible to set both using the resource name, it would require a more complex implementation of the creation (if name is not set, use resourceName, if it's set, use that), but I wonder if that could be an issue where the resource name accepts certain characters and the Pulumi name doesn't; need to investigate that.

> Btw, _really_ great idea to use Myriad here as you have done. Well done!
> I used Myriad in an early alpha of [SqlHydra](https://github.com/JordanMarr/SqlHydra) to generate records from SQL Server SSDT .dacpac file, but have since pivoted to make it a dotnet tool instead.

Thank you, it was fun using it despite the lack of documentation (there and on Fantomas), they are awesome projects, but the learning curve it's steep without many examples.

**Comment by JordanMarr** [comment]
I'm fine with adding both `name` and `resourceName`, so you can close this too if you want to.
