### ISSUE TITLE
How to set AppService Identity

### ISSUE THREAD

**Issue by JordanMarr** [UnoSD/Pulumi.FSharp.Extensions#8]
I am trying to set a web [AppService](https://www.pulumi.com/docs/reference/pkg/azure/appservice/appservice/) `Identity` property, but the `appService` computation expression doesn't have an `identity` custom operation. 

I'm trying to set it to "SystemAssigned" per [this example](https://github.com/pulumi/examples/blob/master/classic-azure-cs-msi-keyvault-rbac/AppStack.cs) so that I can give it access to a KeyVault resource.

Is there a way to set the identity?

**Comment by UnoSD** [comment]
for code readability, the complex properties of the resources are nested computational expressions; when you are unsure on how to set some values, look at the code documentation:

![image](https://user-images.githubusercontent.com/1582987/123551980-08dbe280-d76c-11eb-9ba7-67f23840c74c.png)

tooltips are not well formatted on Rider, but if you use VS or VSCode that should be more readable and you will see what's an operation and what's a different computational expression like in the example

**Comment by JordanMarr** [comment]
Wow that so cool! Until this project I didn't even know it was possible to embed CEs in this way.
Thank you
