### ISSUE TITLE
Great job..

### ISSUE THREAD

**Issue by JordanMarr** [UnoSD/Pulumi.FSharp.Extensions#9]
Once again, amazing job on this library! 

Myriad is a steep learning curve, I know; but the fact that you are generating the CEs makes this library incredibly reliable and resilient. Also, the embedded computation expressions make it so clean and a joy to use. 

I only had to fallback to the base Pulumi API once, and that was because I had a pre-existing resource group that I needed to import via `pulumi import`, so I needed to create it with the `Protect = true` option:

```F#
    let rgName = $"my-resourcegroup"
    let rg = 
        Pulumi.AzureNative.Resources.ResourceGroup(
            rgName, 
            Pulumi.AzureNative.Resources.ResourceGroupArgs(
                Location = pIn "northcentralus",
                ResourceGroupName = pIn rgName
            ), Pulumi.CustomResourceOptions(Protect = true))
```

But I was able to do _everything else_ via your CEs.  🎉🎉

**Comment by UnoSD** [comment]
thank you! the support for import is something I was planning on working on a while back, but then I got really busy and I had to drop contributions, it's likely to be next on my backlog when I get some time to work on this again.

on a side note, there is a solution to avoid that, I do `pulumi import --protect=false` and that does not need the protection flag in code then.
